export type Recipe = {
	steps: string[]
	quantizedIngredients: string[]
	calories: number
	title: string
	image: string
}

export const RECIPES: { [key: string]: Recipe } = {
	"super-veggie": {
		calories: 379,
		image: "/img/meals/super-veggie.jpeg",
		quantizedIngredients: [
			"45 g dry & 150 g cooked black lentils",
			"250 g broccoli (head & stalk)",
			"150 g cauliflower",
			"50 g shiitake or maitake mushrooms",
			"1 clove garlic",
			"3 g ginger root",
			"1 lime",
			"1 tbsp cumin powder",
			"1 tbsp apple cider vinegar",
			"1 tbsp hemp seeds",
			"after prep, 1 tbsp evoo (+120 cal)",
		],
		title: "Super Veggie",
		steps: [
			"Weigh vegetables. Place broccoli, cauliflower, mushrooms (maitake or shiitake), ginger, and garlic in boiling water*. Boil until tender (7–9 min). Steaming is also acceptable.",
			"Lentils: bring the water to boil in a medium saucepan. Add lentils. Reduce heat to low and cook uncovered for 18–20 minutes or until tender. Place in a colander to drain and rinse under cold water.",
			"You can choose to blend or keep whole pieces.",
			"If you choose to blend, place the following in a high-speed blender: 1 Tbsp of dried cumin, 1 Tbsp apple cider vinegar, 1 fresh lime, cooked black lentils, and strained cooked vegetables. Blend until it becomes thick soup. Can also serve as shown in the picture.",
			"If needed, add some of the vegetable water (or steaming water) to thin out the texture.",
			"Top with 1 Tbsp hemp seeds and 1 Tbsp EVOO.",
		],
	},
	"nutty-pudding": {
		calories: 433,
		image: "/img/meals/nutty-pudding.jpg",
		quantizedIngredients: [
			"50-100 ml nut milk",
			"3 tbsp ground macadamia nuts",
			"2 tsp ground walnuts",
			"2 tbsp chia seeds",
			"1 tsp ground flaxseed",
			"1⁄4 brazil nut",
			"1 tbsp cocoa powder",
			"1 tsp sunflower lecithin",
			"1⁄2 tsp ceylon cinnamon",
			"1⁄2 cup berries",
			"3 cherries",
			"2 oz pomegranate juice",
			"1 tbsp evoo (consume separately)",
		],
		title: "Nutty Pudding",
		steps: [
			"Add 50–100 mL almond / macadamia milk based upon desired consistency.",
			"Add walnuts, macadamia nuts, ground flax seeds, chia seeds (obtain the highest nutritional value by buying and grinding seeds).",
			"Add cocoa powder, sunflower lecithin, and cinnamon.",
			"Add 3 cherries, 1⁄2 cup of berries (save half for topping) and pomegranate juice.",
			"Mix on high for 2 minutes.",
			"Pour into a dish.",
			"Add the rest of the berries.",
			"Optional: Add 30–60 grams of pea protein.",
		],
	},
	"buddha-bowl": {
		calories: 450,
		image: "/img/meals/buddha-bowl.jpg",
		quantizedIngredients: [
			"100 gr de japanese sweet potato",
			"30 gr asparagus",
			"50 gr leaves kale",
			"30 gr de red pepper",
			"30 gr carrots",
			"10 gr walnuts",
			"30 gr de of cilantro",
			"10 gr of green onions",
			"1 lemon",
			"30 gr de dill",
			"30 gr de beans",
			"1 tbsp apple cider vinegar",
			"½/ tsp cumin seeds",
		],
		title: "Buddha Bowl",
		steps: [
			"Poke a few holes in the sweet potato and slightly cover with EVOO roast the japanese sweet potato for 45 - 1 hour at 400 degrees. Once done roasted, pull out of the oven, cut in half and top with green onion and cilantro.",
			"Once the sweet potato is done, roast the red pepper in the oven for 25 - 30 mins. Thinly slice the pepper once it's done roasting. Trim off the woody ends of the asparagus and boil 1 - inch water in a large skillet for 2 - 5 minutes.",
			"Rinse and drain the white beans and squeeze 1 lemon and a handful of chopped dill. Shred the carrots and massage with apple cider vinegar and cumin seeds.",
			"Chop the kale, add a splash of EVOQ and massage with your handsuntil softens.",
			"Assemble the bowl with the sweet potato, asparagus, red pepper, bean salad, kale and shredded carrots. Top with toasted walnuts and a squeeze of lemon.",
		],
	},
	"roasted-veggie-lettuce-wraps": {
		calories: 300,
		image: "/img/meals/roasted-veggie-lettuce-wraps.jpg",
		quantizedIngredients: [
			"1 white sweet potato",
			"1 small head of cauliflower",
			"1 bulb fennel",
			"1 white sweet onion",
			"1 lemon",
			"1 tbsp evoo",
			"1 small cube ginger",
			"1 tbsp smoked paprika",
			"1 tsp cumin powder",
			"1⁄2 tsp pepper",
			"3 tbsp fresh herbs (oregano, thyme, + rosemary, etc.)",
			"1 head butter lettuce",
			// POMEGRANATE RELISH
			"4 radishes",
			"1⁄4 cup pomegranate seeds",
			"1 jalapeño",
			"1 big handful mint leaves",
			"1⁄4 cup toasted pumpkin seeds",
		],
		title: "Roasted Veggie Lettuce Wraps",
		steps: [
			"Chop the sweet potato, cauliflower, fennel, and white onion. Combine and place on a baking sheet. Drizzle the EVOO and squeeze the lemon juice on top of the veggies. In a small bowl, combine the smoked paprika, cumin powder, and pepper. Grate the ginger. Sprinkle the seasoning, ginger, and fresh herbs on top of the veggies. Give it a good toss.",
			"Bake in the oven on 350° F for 45 minutes or until the veggies are tender.",
			"While baking, finely chop the radishes and mint. Toss together in a small bowl with the pomegranate seeds for the pomegranate relish.",
			"Wash the butter lettuce and lay out 6–8 leaves for wraps.",
			"To assemble, add 1⁄2 cup of roasted veggies, a spoonful of the pomegranate relish, a few slices of jalapeño, and a sprinkle of toasted pumpkin seeds.",
			"Thinly slice the jalapeño and chop the toasted pumpkin seeds.",
		],
	},
	"blood-orange-and-fennel-salad": {
		calories: 250,
		image: "/img/meals/blood-orange-and-fennel-salad.jpg",
		quantizedIngredients: [
			"1 blood orange",
			"1 lemon",
			"1 bulb fennel",
			"1⁄2 red onion",
			"handful of mint",
			"1⁄4 cup pomegranate seeds",
			"1 cup your choice of greens (kale, spinach, mixed greens, romaine)",
			"1⁄4 cup toasted slivered almonds",
			"1⁄2 cup white beans (or a bean of your choice)",
			"1 tsp evoo",
		],
		title: "Blood Orange + Fennel Salad",
		steps: [
			"Cut the stalks off the fennel. Peel off any outer layers and thinly slice or use a mandoline. Place in a large mixing bowl and set aside.",
			"Peel the blood orange and the orange pith and any white membrane. Slice the orange in chunks. Add to the bowl.",
			"Thinly slice the red onion and cut the mint. Add both to the bowl",
			"Top with EVOO, pomegranate seeds, toasted almonds, beans, and a handful of mint. Squeeze the juice of one lemon, and toss.",
		],
	},
	"roasted-beets-and-green-lentils-and-wilted-chard": {
		calories: 400,
		image: "/img/meals/roasted-beets-and-green-lentils-and-wilted-chard.png",
		quantizedIngredients: [
			"1⁄2 cup green lentils",
			"4 cups rainbow or swiss chard",
			"handful of fresh herbs-basil, dill, mint",
			"1⁄4 pepper",
			"1⁄4 chipotle powder",
			"1 tbsp italian seasoning",
			"1 clove of garlic",
			"1 large shallot",
			"3 large beets",
			"3 tbsp walnuts",
			 "1 tbsp evoo",
		],
		title: "Roasted Beets + Green Lentils + Wilted Chard",
		steps: [
			"Peel the whole beets with a vegetable peeler and cut into chunks. Place ton baking sheet, cover with 1 Tbsp EVOO, and roast in the oven at 400°F–425°F in the oven for 35–40 minutes or until golden brown.",
			"Add 4 cups of water and 1 cup of lentils to a pot. Bring to a boil, reduce to a low simmer, and cook 18 minutes. Drain and rinse. Sprinkle with Italian seasoning.",
			"In a pan, sauté shallot and garlic with a dash of EVOO, and add a mound of chard (about four cups packed). Gently wilt for 1–4 minutes.",
			"Toast the walnuts on low heat until browned, about 3–4 minutes.",
			"In a bowl, combine the wilted chard, lentils, roasted beets, and toasted walnuts.",
			"Toss in a handful of chopped basil or dill. Season with pepper and a dash of chipotle powder.",
		],
	},
	"roasted-cabbage-steaks-and-sweet-potato-mash": {
		calories: 350,
		image: "/img/meals/roasted-cabbage-steaks-and-sweet-potato-mash.jpg",
		quantizedIngredients: [
			"1⁄4 head purple cabbage",
			"1 orange sweet potato",
			"1⁄2 cup unsweetened",
			"almond milk",
			"handful of parsley",
			"pumpkin seeds",
			"1⁄2 tsp cinnamon",
			"1⁄2 tsp nutmeg",
			"1⁄2 tsp pumpkin seeds",
			"1⁄4 cup toasted walnuts or pecans",
			"1 lemon",
			"1 tsp evoo",
			"1⁄2 chipotle powder",
			"1⁄2 paprika",
			"1⁄2 onion powder",
		],
		title: "Roasted Cabbage Steaks + Sweet Potato Mash",
		steps: [
			// SWEET POTATO MASH
			"Peel the sweet potato and cut it into 1–inch cubes. Boil the sweet potatoes for about 10–15 minutes or until fork-tender.",
			"Drain the sweet potatoes, place in bowl, and mash with fork. You can mash them super smooth or leave them chunkier. Slowly add in the almond milk in small amounts at a time until desired consistency.",
			"Add in the cinnamon and nutmeg and stir until smooth.",
			"Toast the walnuts or pecans in a pan at low heat for 3–4 minutes and crumble on top.",
			// ROASTED CABBAGE STEAKS
			'Remove and discard the outer leaves. Firmly press down on cabbage with one hand and cut an inch-thick "steak." Place on a baking sheet.',
			"Drizzle with EVOO. Generously sprinkle the chipotle powder, paprika, and onion powder on the steaks.",
			"Roast in the oven at 400°F for 20–30 minutes or until tender/golden brown.",
			"On a plate, scoop a few spoonfuls of the sweet potato mash and smooth flat. Lay the cabbage steaks on top of the mash. Chop and sprinkle some parsley or any other fresh herb. Finish with a squeeze of lemon juice.",
		],
	},
	"sweet-potato-and-mushroom-toast": {
		calories: 400,
		image: "/img/meals/sweet-potato-and-mushroom-toast.jpg",
		quantizedIngredients: [
			"1 orange sweet potato",
			"1-2 oyster mushrooms",
			"handful of another type of mushroom (shitake, cremini, etc.)",
			"1⁄2 avocado",
			"1⁄2 tbsp coconut aminos",
			"zest of 1 orange",
			"1 lime",
			"1 clove garlic",
			"1 tbsp evoo",
			"1 tsp smoked paprika",
			"1⁄2 toasted sesame seeds",
			"1⁄2 cup arugula",
			"sprinkle dried nori",
		],
		title: "Sweet Potato + Mushroom Toast",
		steps: [
			// SWEET POTATO TOAST
			"Wash and scrub the sweet potato. Slice the sweet potato lengthwise in 1⁄2–nch slices.",
			"Drizzle with EVOO and roast at 400°F for 30–45 minutes.",
			// MUSHROOM TOPPER
			"Shred the oyster mushrooms with a fork (they will look stringy), and chop up additional mushrooms. Squeeze juice of 1 lime. Sprinkle with smoked paprika (coconut aminos optional).",
			"Chop up 1 clove garlic. Heat up EVOO on medium. Add chopped garlic to the pan for 1–3 minutes.",
			"Add in mushrooms and cook on low heat for 6–8 minutes or until mushrooms are tender.",
			// ASSEMBLE TOAST
			"Mash 1⁄2 whole avocado in a bowl.",
			"On a plate add the arugula and lay out the sweet potato toasts. Top each toast with a spoonful of avocado and mushrooms. Sprinkle with toasted sesame seeds. Crush some nori on top, and add orange zest.",
		],
	},
	"chickpea-curry-over-greens": {
		calories: 450,
		image: "/img/meals/chickpea-curry-over-greens.jpg",
		quantizedIngredients: [
			"1 tbsp grated fresh ginger",
			"1 clove garlic (chopped)",
			"1 medium scallion (chopped)",
			"1 red pepper",
			"1 white sweet potato",
			"1/2 can chickpeas",
			"1 tbsp evoo",
			"1/2 tsp coconut amino (optional)",
			"1 tbsp (or more) curry powder",
			"1/2 tsp cinnamon",
			"1 cup macadamia nut milk",
			"handful cilantro",
			"1-2 cups baby romaine",
			"1 jalapeno (sliced)",
		],
		title: "Chickpea Curry Over Greens",
		steps: [
			"Sauté the grated ginger, chopped garlic, and chopped scallion in EVOO for 5 minutes or until soft.",
			"Peel and chop the white sweet potato into small chunks and thinly slice the red pepper.",
			"Rinse and drain the chickpeas.",
			"Add in the curry powder, cinnamon, and squeeze of lime into a pot. Stir and sauté for 1–2 minutes.",
			"Add in the pepper, sweet potato, chickpeas, and 1 cup of macadamia nut milk. Bring to a boil, then cover and reduce heat to low. Let cook. Lower temperature and cook for 20–25 minutes or until sweet potatoes are soft.",
			"If desired, add more macadamia nut milk to achieve desired consistency.",
			"Let sit 10–15 minutes before serving.",
			"Scoop the curry mixture over the greens and top with cilantro and sliced jalapeño.",
		],
	},
	"beet-poke": {
		calories: 300,
		image: "/img/meals/beet-poke.jpg",
		quantizedIngredients: [
			"4–5 beets",
			"1–2 purple or watermelon radishes",
			"1⁄2 avocado",
			"1⁄4 mango",
			"1–2 cups of mixed greens",
			"2 limes",
			"sprinkle of toasted sesame seeds",
			"handful green onions",
			"handful cilantro",
			"handful microgreens (radish, pea shoots, sprouts)",
			"1 tsp evoo",
			"1⁄2 tbsp coconut aminos",
		],
		title: "Beet Poke",
		steps: [
			"Wash & peel the beets. Cut into 1–inch cubes. Boil in water for 20–25 minutes until tender. Drain and rinse.",
			"Chop the green onions and cilantro.",
			"In a bowl, combine the cooked chopped beets, handful of green onions, chopped cilantro, spoonful of sesame seeds, coconut aminos, juice of 2 limes, and EVOO.",
			"Refrigerate and let sit for 10–15 minutes.",
			"Slice the mango, avocado, and radish.",
			"Assemble on a plate with 1–2 cups of greens, mango, avocado, beet poke, sliced radish, and your favorite microgreens.",
		],
	},
	"collard-green-wraps-and-red-pepper-dip": {
		calories: 350,
		image: "/img/meals/collard-green-wraps-and-red-pepper-dip.jpg",
		quantizedIngredients: [
			"1 bunch collard greens",
			"a bowl of your favorite mixed veggies, like: shredded purple cabbage, carrots, cucumber, cilantro microgreens",
			"1/2 avocado",
			"red pepper dip: 1 red pepper, 1/2 cup macadamia nuts (soaked for 1-2 hours)",
			],
		title: "Collard Green Wraps + Red Pepper Dip",
		steps: [
			"Cut the stems off the collard green leaves and then shave the stem down using a small knife so that it’s flat. This helps prevent the leaf from breaking at the end and making it easier to roll up.",
			"Drop your collard greens in a pot of boiling water for 1–2 minutes to soften them.",
			"Thinly slice your chosen raw vegetables.",
			'Add the sliced vegetable filling to the middle-bottom of a collard green leaf "wrap."',
			"Carefully roll the collard green wrap just like you would with a burrito, tucking in the ends as you go so that the filling stays inside. Let these chill in the fridge while you make the red pepper dip.",
			"Cut the red pepper in half vertically and remove its core and seeds. Place the halves face down on a baking sheet and roast at 400°F for 20–30 minutes or until the pepper is soft.",
			"In a blender, blend roasted pepper, 1⁄2 cup of macadamia nuts, and a little water. Add 1 Tbsp at a time until you reach the desired consistency.",
			"Pull the wraps out of the refrigerator and dip in the red pepper sauce.",
		],
	},
	"roasted-bok-choy-and-japanese-sweet-potato": {
		calories: 400,
		image: "/img/meals/roasted-bok-choy-and-japanese-sweet-potato.jpg",
		quantizedIngredients: [
			"3–4 baby bok choy",
			"1⁄2 tbsp chopped walnuts",
			"handful of chopped green onions",
			"handful of cilantro or parsley",
			"smoked paprika",
			"1⁄2 juice of orange",
			"1 tsp tahini",
			"1–2 lemons",
			"chipotle powder",
			"1 japanese sweet potato",
			"1⁄2 tbsp evoo",
		],
		title: "Roasted Bok Choy + Japanese Sweet Potato",
		steps: [
			"Rinse and chop the Japanese sweet potato in half and then in thirds. Coat with EVOO, place face down on a baking sheet, and bake at 400°F for 45–60 minutes or until soft. 30 minutes in, turn the sweet potatoes over.",
			"Rinse and slice the bok choy in half. Coat with the juice of 1⁄2 orange. Roast at 400°F for 20–25 minutes or until golden brown on the edges.",
			"Toast the walnuts and chipotle powder for 5–10 minutes over medium low heat or until the walnuts are browned.",
			"Mix 1 Tbsp of tahini with the juice of 1–2 lemons. Add 1 Tbsp of water at a time until you reach your desired consistency.",
			"Place the bok choy on a plate and top with chopped walnuts, cilantro, and tahini sauce. Sprinkle with smoked paprika and serve with baked Japanese sweet potatoes.",
		],
	},
}
